name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_NAME: ${{ github.repository }}
  TAGS: latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Install cosign
        uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 # v3.1.1

      - name: Build Application
        run: ./mvnw package 

      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          containerfiles: |
            ./src/main/docker/Dockerfile.jvm

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.REGISTRY }}

      - name: Push to Container Repository
        uses: redhat-actions/push-to-registry@v2
        id: push-to-registry
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          registry: ${{ env.REGISTRY }}
      
      - name: Sign Image
        run: cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.push-to-registry.outputs.digest }}
  
      - name: Attach SBOM
        run: cosign attest --predicate=./target/classes/META-INF/maven/com.redhat.meetups/nljug-sigstore-demo-app/license.spdx.json -y --type=spdxjson ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.push-to-registry.outputs.digest }}

